name: nytgames
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - pytorch
  - pip
  - pip:
    - gymnasium
    - huggingface_hub
    - google-generativeai
    - openai
    - stable-baselines3
